### ISSUE TITLE
BUG: Jacoco report not generated when using Java 17

### ISSUE THREAD

**Issue by kavithatiru** [cicirello/jacoco-badge-generator#120]

**Comment by cicirello** [comment]
Do you have any more information? Based on the issue title alone, I'd guess it isn't an issue with the action because it doesn't generate JaCoCo reports. You need to run Jacoco in some other way first.

Is this in a public repository? If so, can you post a link to it?

**Comment by cicirello** [comment]
@kavithatiru I need more information in order to determine if there is an issue with the action or not. E.g. did you run it in a public repo? If so, the action run log would be helpful. Did you run the CLI version locally? If so, details of your build (e.g. Maven or gradle configuration, etc).

I'm closing this for now, since the title of your issue, if accurate, is not an issue with the action. It doesn't generate jacoco reports. Your build needs to do that first, which depends on your build tool.

Feel free to open a new issue with details of the problem you are having.
