### ISSUE TITLE
BUG: Maven multi-module project can't find 'target/site/jacoco/jacoco.csv'

### ISSUE THREAD

**Issue by cprudhom** [cicirello/jacoco-badge-generator#16]
**Describe the bug**
I manage a multi-module maven project and when it comes to run cicirello/jacoco-badge-generator@v2.0.1, I got the following error: 
```
FileNotFoundError: [Errno 2] No such file or directory: 'target/site/jacoco/jacoco.csv'
```
Indeed, the parent artefact has no `target/site/jacoco` directory whereas modules have.

**To Reproduce**
1. First, create a dummy mutli-module project like [this one](https://www.baeldung.com/maven-multi-module)
2. Then define at least one test in each sub-project
3. Finally define GH actions including cicirello/jacoco-badge-generator@v2.0.1

**Expected behavior**
I suppose the default behavior should scan for all target directories, from parent to children to look for all CSV files.

**Relevant System Info (please complete the following information):**
 - Version: cicirello/jacoco-badge-generator@v2.0.1

Best regards,
CP

**Comment by cprudhom** [comment]
I suppose I could also merge `jacoco.csv` files using [jacoco:merge](https://www.jacoco.org/jacoco/trunk/doc/merge-mojo.html)...

**Comment by cicirello** [comment]
@cprudhom It looks like with a multi-module project that each of the sub-projects have their own target directory and that they are otherwise structured the same.  E.g., sub1/target/site/jacoco/jacoco.csv, sub2/target/site/jacoco/jacoco.csv, etc.  

I'm thinking of two possible solutions:
1. Add an input to the action, something like multi-module.  If true, check all subdirectories for `target/site/jacoco/jacoco.csv` (well, actually for the existing `jacoco-csv-file` action input which defaults to that). This assumes that the project is either using the default target directory or that if it was changed then it was changed consistently for all subprojects. I think that is a reasonable assumption since it would be confusing if different subprojects had differently named target directories.
2. Option 2 would be the same as option 1 above, but to automatically check for subprojects, without introducing an action input to turn that on. 

The main drawback of Option 2 is that if someone wanted to compute coverage separately for each subproject they wouldn't be able to do so.  With Option 1, they still can by keeping multi-module set to false, and running the existing action multiple times once for each subproject (just setting the `jacoco-csv-file` action input appropriately for each, such as `sub1/target/site/jacoco/jacoco.csv', etc). And someone who wants to combine the coverage calculation can by leaving `jacoco-csv-file` as the default, and then setting the proposed multi-module input to true.

What are your thoughts on these alternatives?  Any others you can think of?

**Comment by cprudhom** [comment]
@cicirello Thank you for the quick answer and proposals. I would vote for 1 for the reasons you gave.
Alternatively what about listing the desired target directories (or files) as input of the action?
Sorry if that's not technically sound, I quite new to GitHub actions I started yesterday.

Another point of vigilance concerns matrix based jobs since each job has its process (which is my case), and I don't know (I don't try out yet) wether coverage statistics will be merged ? But that might be another issue.

**Comment by cicirello** [comment]
@cprudhom I like your idea of listing the directories or files. It is more flexible than my initial ideas. E.g., if someone wanted to report coverage for a subset of their modules but not all, they can just list the specific jacoco reports.

I think I can do this without adding any new inputs as well. Just check the existing jacoco-csv-file input for a list of paths.

**Comment by cprudhom** [comment]
Is `*.csv` the best option? It seems that JaCoCo also dealt with `*.exec` file (which is the one targeted by `jacoco:merge`).

**Comment by cicirello** [comment]
I'm not entirely sure what the `*.exe` file is, but I think it relates to the actual running of jacoco. It's definitely a binary file, and I'm assuming it is an executable (unless they are using the extension in an unusual way).

For extracting the data needed to compute coverage percentages, either the `jacoco.csv` or the `jacoco.xml` files are probably the easiest way. They contain the same data. I'm not sure if one is better than the other.  I went with the `csv` because at the time it seemed simpler to parse, but `xml` is easy enough to parse as well, especially since there are libraries for that.  The main potential downside to using the `csv` is that if they decide to change the order of the columns in a future release it would affect the parser, where as there is probably less such risk with the `xml` reports.

**Comment by cicirello** [comment]
I'm mistaken as to what the `*.exec.` file is.  I've assumed it was some sort of executable for generating the reports.  I poked around a bit, and it appears to actually be the coverage report, or possibly the raw data, in a binary format.  The `report` goal uses it to generate the various other forms of the report, such as the html version, which is easiest to read by people, as well as the xml and csv versions.  Probably any more sophisticated analysis of the data would likely be best using the `exec` since that presumably has all of the raw data needed to map the results down to the specific lines that were missed, etc.  But to just compute code coverage, it is certainly simpler to just use the csv or xml data.

**Comment by cicirello** [comment]
@cprudhom I just released a new version (v2.1.0) that supports multi-module projects.  It works the same as before for single module projects.  But the `jacoco-csv-file` input now supports being passed any number of csv files so that it can also handle multi-module projects.  There is a new example workflow in the documentation related to this: https://github.com/cicirello/jacoco-badge-generator#multi-module-example-workflows

**Comment by cprudhom** [comment]
Very quick patch, thank you !
I'll have a look asap.

**Comment by cicirello** [comment]
You're welcome. It was an easy fix, 3 lines of code, and the rest was adding test cases and editing documentation.
