### ISSUE TITLE
Feature Req: add exact coverage value, with virtually infinite precision into some hidden field of JSON and SVG for future comparisons

### ISSUE THREAD

**Issue by alex-schwartzman-at-stratify** [cicirello/jacoco-badge-generator#38]
In a huuge projects, 0.1% might include a couple of factories implementations plus minor bugfixes. Therefore, one decimal place precision is counterproductive - someone might spend significant effort, adding coverage by 0.04%, and someone else might just add some non-covered reducing overall coverage by 0.05%. After rounding to the first decimal place, the initial value, the value after the first contributor, and reduced value after the second one are undistinguishable. That discourages the first contributor from writing any more tests.

Please, add the input parameter "rounding" to the plugin.

**Comment by cicirello** [comment]
Are you requesting an option to round instead of truncating? For example, right now 89.85 will truncate to one decimal as 89.8 whereas rounding we'd end up with 89.9. Or do you want an input to control number of decimal places?

**Comment by alex-schwartzman-at-stratify** [comment]
What I'm requesting is to add configurably more digits. Like, if we have this coverage reported: `23.55991131279494%`, then, depending on the configuration, we'll see in the badge:

`rounding: 0` => `24%`
`rounding:  1` => `23.6%`
`rounding:  2` => `23.56%`
`rounding:  3` => `23.560%`
`rounding:  4` => `23.5599%`
`rounding:  5` => `23.55991%`
`rounding:  6` => `23.559911%`
`rounding:  7` => `23.5599113%`

Why it is important - is that we already have 100000 lines of the code in the project, and we'd like to catch the difference in the single line coverage, which means we need at least precision of 4 digits after decimal point, like `23.5599`

**Comment by cicirello** [comment]
I see. There are actually two changes here (both doable) and your example use case gives me an idea for a third that may actually better fit (either by itself or in addition to) your use case.

First, right now the precision in the percentages is 1 decimal place. So one of the changes would be a configurable precision.

Second, currently the displayed coverage is truncated rather than rounded. The rationale is to avoid coverage less than some target minimum from appearing to meet the target minimum. Also to prevent something like 99.99% from showing as 100%. So an additional change would be to add an option to choose rounding rather than truncation.

A third possible change I see from your use case relates to how the action currently gets the prior coverage for use in the feature that compares current coverage to old for use in failing workflows if coverage declined. Currently, it relies on the displayed coverage which has been truncated. It should be possible to actually store the computed percentage, as is, in the badge or JSON for use by that feature. E.g. in the JSON as an extra field or in the SVG as a comment or something similar that is not rendered. In combination with the configurable precision, you'd be able to display in badge at one precision but use full floating-point precision in the decreased coverage check.

**Comment by alex-schwartzman-at-stratify** [comment]
Hello, Vincent.

Thanks for dissecting and analyzing my request and understanding the problem. 

Indeed the third option would do the best job for my case. Requirement for the rounding - maybe we can drop it, as truncating seems to be a smarter choice. The change of the display precision is not required anymore as soon as there is an extra field in the JSON (not rendered) with an exact number. 

Alex

**Comment by cicirello** [comment]
If extra fields cause a validation issue with shields, then your idea of an additional JSON file sounds like the way to go. I'll add an input to control whether it is generated so users don't get surprised by an unexpected additional file.

**Comment by cicirello** [comment]
@alex-schwartzman-at-stratify I just released an update for this, v2.5.0. It is disabled by default. Use `generate-summary: true` to enable. You can change the filename with `summary-filename` if you don't like the default `coverage-summary.json`.

I might add a configurable precision for the percentages shown in the badges as well.

**Comment by alex-schwartzman-at-stratify** [comment]
Hello, Vincent.

That's cool! Thanks a lot!

I'll try it out now straight away.

Alex.

PS. From my side, I'm absolutely happy with the summary file. It addresses my problem much more efficiently than the configurable precision in the badges.

**Comment by alex-schwartzman-at-stratify** [comment]
Just small semantic note - a new parameter "generate-summary" not only *generates* the summary but also *compares* two summaries, to detect the reduced coverage.  :) 

Some random user of the plugin might get confused by the word "generate" and not expect that all the remaining side-effects will also take place.

**Comment by cicirello** [comment]
Unless they set either `fail-on-coverage-decrease: true` or `fail-on-branches-decrease: true`, the only thing `generate-summary: true` will do is generate the summary file. The comparison to the previous summary only happens if they use one of those other options in combination. I figured that it is possible someone might just want the calculated percentages for some other reason.

The fail on decrease features will use the new summary report if it exists since that is more accurate, but will also continue to work if the summary feature isn't used as well by just using the less accurate badge percentage.

**Comment by alex-schwartzman-at-stratify** [comment]
Validated the feature:

One-liner change:
```@@ -8,6 +8,7 @@ import org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAu
 public class OrchestratorApplication {
 
     public static void main(String[] args) {
+        System.out.println(100500);
         SpringApplication.run(OrchestratorApplication.class, args);
     }
 
```

which is, of course, not covered by the test, yields:

```
Coverage decreased from 64.44058976582826 to 64.39869989165764
Failing the workflow run.
```

indeed, the comparison was done between the summary files, and 0.05% difference was caught successfully

QA: Passed

Alex
